-- ORGANISATION ROLE TABLE ACCESS


GRANT SELECT ON `{{BLOTTO_DB}}`.`ANLs`
TO '{{BLOTTO_ORG_USER}}'
;

GRANT SELECT ON `{{BLOTTO_DB}}`.`Cancellations`
TO '{{BLOTTO_ORG_USER}}'
;

GRANT SELECT ON `{{BLOTTO_DB}}`.`Changes`
TO '{{BLOTTO_ORG_USER}}'
;

GRANT SELECT ON `{{BLOTTO_DB}}`.`Supporters`
TO '{{BLOTTO_ORG_USER}}'
;

GRANT SELECT ON `{{BLOTTO_DB}}`.`Updates`
TO '{{BLOTTO_ORG_USER}}'
;

